[general]
import = ["~/.config/alacritty/gruvbox_dark.toml"]

[window]
# decorations = "Buttonless"
opacity = 0.8
blur = true

[scrolling]
multiplier = 1

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 16.0

[keyboard]
bindings = [
  { key = "Left", mods = "Control|Shift", action = "SelectPreviousTab" },
  { key = "Right", mods = "Control|Shift", action = "SelectNextTab" },
  { key = "Enter", mods = "Command", action = "ToggleFullscreen" },
  { key = "Enter", mods = "Command|Shift", action = "ToggleViMode" },
  # { key = "w", mods = "Command", action = "ReceiveChar" },
  # { key = "w", mods = "Command|Shift", action = "Quit" },
  # { key = "c", mods = "Command", action = "ReceiveChar" },
  # { key = "c", mods = "Command|Shift", action = "Copy" },
]
