[general]
import = [
  "~/.config/alacritty/gruvbox_dark.toml",
  "~/.config/alacritty/keybindings-nvim.toml",
]

[env]
LANG = "zh_CN.UTF-8"
LC_COLLATE = "zh_CN.UTF-8"
LC_CTYPE = "zh_CN.UTF-8"
LC_MESSAGES = "zh_CN.UTF-8"
LC_MONETARY = "zh_CN.UTF-8"
LC_NUMERIC = "zh_CN.UTF-8"
LC_TIME = "zh_CN.UTF-8"
LC_ALL = "zh_CN.UTF-8"
TERM = "xterm-256color"

[window]
# decorations = "Buttonless"
opacity = 0.8
blur = true

[scrolling]
multiplier = 1

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 16.0
