[general]
import = [
  "~/.config/alacritty/gruvbox_dark.toml",
  "~/.config/alacritty/keybindings-nvim.toml",
]

[window]
# decorations = "Buttonless"
opacity = 0.8
blur = true

[scrolling]
multiplier = 1

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 16.0
